//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ookii.Dialogs.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ookii.Dialogs.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to load the progress dialog animation: {0}.
        /// </summary>
        internal static string AnimationLoadErrorFormat {
            get {
                return ResourceManager.GetString("AnimationLoadErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The credential target may not be an empty string..
        /// </summary>
        internal static string CredentialEmptyTargetError {
            get {
                return ResourceManager.GetString("CredentialEmptyTargetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred acquiring credentials..
        /// </summary>
        internal static string CredentialError {
            get {
                return ResourceManager.GetString("CredentialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PromptForCredentialsWithSave has not been called or the credentials were modified after the call..
        /// </summary>
        internal static string CredentialPromptNotCalled {
            get {
                return ResourceManager.GetString("CredentialPromptNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The task dialog already has a non-custom button with the same type..
        /// </summary>
        internal static string DuplicateButtonTypeError {
            get {
                return ResourceManager.GetString("DuplicateButtonTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The task dialog already has an item with the same id..
        /// </summary>
        internal static string DuplicateItemIdError {
            get {
                return ResourceManager.GetString("DuplicateItemIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string FileNotFoundFormat {
            get {
                return ResourceManager.GetString("FileNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to retrieve the root folder..
        /// </summary>
        internal static string FolderBrowserDialogNoRootFolder {
            get {
                return ResourceManager.GetString("FolderBrowserDialogNoRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The current operating system does not support glass, or the Desktop Window Manager is not enabled..
        /// </summary>
        internal static string GlassNotSupportedError {
            get {
                return ResourceManager.GetString("GlassNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid filter string,.
        /// </summary>
        internal static string InvalidFilterString {
            get {
                return ResourceManager.GetString("InvalidFilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The id of a task dialog item must be higher than 0..
        /// </summary>
        internal static string InvalidTaskDialogItemIdError {
            get {
                return ResourceManager.GetString("InvalidTaskDialogItemIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The item is not associated with a task dialog..
        /// </summary>
        internal static string NoAssociatedTaskDialogError {
            get {
                return ResourceManager.GetString("NoAssociatedTaskDialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot change the id for a standard button..
        /// </summary>
        internal static string NonCustomTaskDialogButtonIdError {
            get {
                return ResourceManager.GetString("NonCustomTaskDialogButtonIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preview.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The progress dialog is not shown..
        /// </summary>
        internal static string ProgressDialogNotRunningError {
            get {
                return ResourceManager.GetString("ProgressDialogNotRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The progress dialog is already running..
        /// </summary>
        internal static string ProgressDialogRunning {
            get {
                return ResourceManager.GetString("ProgressDialogRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A custom button or radio button cannot have an empty label..
        /// </summary>
        internal static string TaskDialogEmptyButtonLabelError {
            get {
                return ResourceManager.GetString("TaskDialogEmptyButtonLabelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cross-thread operation not valid: Task dialog accessed from a thread other than the thread it was created on while it is visible..
        /// </summary>
        internal static string TaskDialogIllegalCrossThreadCallError {
            get {
                return ResourceManager.GetString("TaskDialogIllegalCrossThreadCallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The task dialog item already belongs to another task dialog..
        /// </summary>
        internal static string TaskDialogItemHasOwnerError {
            get {
                return ResourceManager.GetString("TaskDialogItemHasOwnerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The task dialog must have buttons..
        /// </summary>
        internal static string TaskDialogNoButtonsError {
            get {
                return ResourceManager.GetString("TaskDialogNoButtonsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The task dialog is not current displayed..
        /// </summary>
        internal static string TaskDialogNotRunningError {
            get {
                return ResourceManager.GetString("TaskDialogNotRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The task dialog is already being displayed..
        /// </summary>
        internal static string TaskDialogRunningError {
            get {
                return ResourceManager.GetString("TaskDialogRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The operating system does not support task dialogs..
        /// </summary>
        internal static string TaskDialogsNotSupportedError {
            get {
                return ResourceManager.GetString("TaskDialogsNotSupportedError", resourceCulture);
            }
        }
    }
}
